# A TOML linter such as https://github.com/tombi-toml/tombi can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [1, 4, 3]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = true
show_symlink   = true
scrolloff      = 5
# Enable the mouse support. Sometimes, it conflicts with tmux and the image preview will disappear when mouse moves.
# Therefore, the mouse move event is not used.
mouse_events = ["click", "scroll"]

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1200
max_height      = 1600
image_filter    = "triangle"
image_quality   = 75
image_delay     = 100
ueberzug_scale  = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = "${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix", block = true },
  { run = 'neovide %s', orphan = true, desc = "Neovide", for = "macos" },
]
open = [
  # { run = 'xdg-open "%1"', desc = "Open", for = "linux" },
  { run = 'open %s', desc = "Open", for = "macos" },
]
reveal = [
  # { run = 'xdg-open "$(dirname "%1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R %s1', desc = "Reveal", for = "macos" },
  # { run = '''exiftool "%1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [{ run = 'ya pub extract --list "%s"', desc = "Extract here", for = "unix" }]
download = [
  { run = "ya emit download --open %S", desc = "Download and open" },
  { run = "ya emit download %S", desc = "Download" },
]
play = [
  { run = 'mpv --force-window "%s"', orphan = true, for = "unix" },
  { run = '''mediainfo "%1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
gimp = [{ run = 'gimp "%s"', orphan = true, desc = "GIMP", for = "macos" }]
acrobat = [{ run = 'open -a "Adobe Acrobat" "%s"', orphan = true, desc = "Acrobat", for = "macos" }]
trash = [
  { run = "ya pub trash-restore --list %S", desc = "Restore selected files" },
  # { run = "ya pub trash-empty --list %S", desc = "Empty trash bin" },
]


[open]
rules = [
  # Folder
  { url = "*/", use = ["open", "reveal"] },
  # Text
  { mime = "text/*", use = ["edit", "reveal"] },
  # Image
  { mime = "image/*", use = ["open", "reveal", "gimp"] },
  # Media
  { mime = "{audio,video}/*", use = ["open", "play", "reveal"] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "reveal"] },
  # JSON
  { mime = "application/{json,ndjson}", use = ["edit", "reveal"] },
  { mime = "*/javascript", use = ["edit", "reveal"] },
  # Empty file
  { mime = "inode/empty", use = ["edit", "reveal"] },
  # pdf
  { mime = "application/pdf", use = ["open", "acrobat", "reveal"] },
  # Virtual file system
  { mime = "vfs/{absent,stale}", use = "download" },
  # Microsoft files
  { url = "*.xlsx", use = ["open", "reveal"] },
  { url = "*.ppt", use = ["open", "reveal"] },
  { url = "*.pptx", use = ["open", "reveal"] },
  { url = "*.doc", use = ["open", "reveal"] },
  { url = "*.docx", use = ["open", "reveal"] },
  # Trash
  { mime = "trash/**", use = ["open", "trash"] },
  # Fallback
  { url = "*", use = ["edit", "open", "reveal"] },

]

[tasks]
file_workers     = 3
plugin_workers   = 5
fetch_workers    = 5
preload_workers  = 2
process_workers  = 5
bizarre_retry    = 3
image_alloc      = 536870912      # 512MB
image_bound      = [10000, 10000]
suppress_preload = false

[plugin]

fetchers = [
  # MIME-type
  { url = "*/", run = "mime.dir", prio = "high", group = "mime" },
  { url = "local://*", run = "mime.local", prio = "high", group = "mime" },
  { url = "trash://*", run = "mime.trash", prio = "high", group = "mime" },
  { url = "remote://*", run = "mime.remote", prio = "high", group = "mime" },
]
spotters = [
  # Multi-file
  { mime = "multi/*", run = "multi" },
  # Trash
  { mime = "trash/**", run = "trash" },
  # Folder
  { url = "*/", run = "folder" },
  # Code
  { mime = "text/*", run = "code" },
  { mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
  # Image
  { mime = "image/{avif,hei?,jxl}", run = "magick" },
  { mime = "image/svg+xml", run = "svg" },
  { mime = "image/*", run = "image" },
  # Video
  { mime = "video/*", run = "video" },
  # Virtual file system
  { mime = "vfs/*", run = "vfs" },
  # Error
  { mime = "null/*", run = "null" },
  # Fallback
  { url = "*", run = "file" },
]
preloaders = [
  # Image
  { mime = "image/{avif,heic,jxl,svg+xml}", run = "magick" },
  { mime = "image/*", run = "image" },
  # Video
  { mime = "video/*", run = "video" },
  # PDF
  { mime = "application/pdf", run = "pdf" },
  # Trash
  { mime = "trash/**", run = "trash" },
  # Font
  { mime = "font/*", run = "font" },
  { mime = "application/vnd.ms-opentype", run = "font" },
]
previewers = [
  { url = "*/", run = "folder" },
  # Code
  { mime = "text/*", run = "code" },
  { mime = "*/{xml,javascript,wine-extension-ini}", run = "code" },
  # JSON
  { mime = "application/{json,ndjson}", run = "json" },
  # Image
  { mime = "image/{avif,heic,jxl,svg+xml}", run = "magick" },
  { mime = "image/*", run = "image" },
  # Video
  { mime = "video/*", run = "video" },
  # PDF
  { mime = "application/pdf", run = "pdf" },
  # Archive
  { mime = "application/{,g}zip", run = "archive" },
  { mime = "application/{tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "archive" },
  # Trash
  { mime = "trash/**", run = "trash" },
  # Font
  { mime = "font/*", run = "font" },
  { mime = "application/vnd.ms-opentype", run = "font" },
  # Fallback
  { url = "*", run = "file" },
]

# Copied from the ouch plugin: https://github.com/ndtoan96/ouch.yazi
prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/tar", run = "ouch" },
  { mime = "application/bzip2", run = "ouch" },
  { mime = "application/7z-compressed", run = "ouch" },
  { mime = "application/rar", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
]


[input]
cursor_blink = false

# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [0, 2, 50, 3]

# create
create_title  = ["Create:", "Create (dir):"]
create_origin = "top-center"
create_offset = [0, 2, 50, 3]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [0, 1, 50, 3]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [0, 2, 50, 3]

# find
find_title  = ["Find next:", "Find previous:"]
find_origin = "top-center"
find_offset = [0, 2, 50, 3]

# search
search_title  = "Search via {n}:"
search_origin = "top-center"
search_offset = [0, 2, 50, 3]

# shell
shell_title  = ["Shell:", "Shell (block):"]
shell_origin = "top-center"
shell_offset = [0, 2, 50, 3]

[confirm]
# trash
trash_title  = "Trash {n} selected file{s}?"
trash_origin = "center"
trash_offset = [0, 0, 70, 20]

# delete
delete_title  = "Permanently delete {n} selected file{s}?"
delete_origin = "center"
delete_offset = [0, 0, 70, 20]

# overwrite
overwrite_title  = "Overwrite file?"
overwrite_body   = "Will overwrite the following file:"
overwrite_origin = "center"
overwrite_offset = [0, 0, 50, 15]

# quit
quit_title  = "Quit?"
quit_body   = "There are unfinished tasks, quit anyway?\n(Open task manager with default key 'w')"
quit_origin = "center"
quit_offset = [0, 0, 50, 15]

[pick]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false
sort_translit  = false
